namespace TimeUnits{
    const long unsigned int MILLISECONDS_IN_SECOND = 1000;
    const long unsigned int SECONDS_IN_MINUTE = 60;
    const long unsigned int MINUTES_IN_HOUR = 60;
    const int SECONDS_IN_HOUR = SECONDS_IN_MINUTE*MINUTES_IN_HOUR;
    const int MILLISECONDS_IN_MINUTE = MILLISECONDS_IN_SECOND*SECONDS_IN_MINUTE;
    const int MILLISECONDS_IN_HOUR = MILLISECONDS_IN_MINUTE*MINUTES_IN_HOUR;
}